### ISSUE TITLE
Shelly 1 PM

### ISSUE THREAD

**Issue by alvaroaparicio** [DeusVermis/heating_control#1]
Hello,

is it possible to use the same with a Shelly 1 PM? what would be the differences for the module 3001_vaillant789?

https://shelly.cloud/products/shelly-1pm-smart-home-automation-relay/

Here the GPIO tasmota template:
https://templates.blakadder.com/shelly_1PM.html

I can see that Shelly RGBW2 LED Controller has a GPIO with PWM1 (37)  -> would this also work?
https://templates.blakadder.com/shelly_RGBW2.html

Thanks

**Comment by DeusVermis** [comment]
The problem is that the voltage from the heating is fluctuating around 20 to 25V DC. The Shelly 1PM needs 24-60V DC, Shelly RGBW2 needs 12V DC or 24V DC according to the data sheets. That's why I would suggest it might not work reliable.
If you try it anyway, please share your outcome.

**Comment by alvaroaparicio** [comment]
Thanks for the feedback.

I could try it with the Shelly RGBW2 and let you know, but i have not clue about the wiring.

From the wiring diagrams i dont know how should it be connected to 7-8-9. Do you have any idea?
https://shelly.cloud/knowledge-base/devices/shelly-rgbw2/

Thanks

**Comment by DeusVermis** [comment]
from my readme
8 - 24VDC supply voltage (would be DC on RGBW2)
9 - GND (would be GND on RGBW2)
From the wiring scheme it looks like R, G, B and W are dimmed GND outputs somehow, but 7 needs to be a dimmed currency output. I am really not sure if this would work! :-\
Do not connect your devices unless you measured it an know what you are doing. Do not crash your devices.

**Comment by alvaroaparicio** [comment]
Ok, thanks. I thought maybe Shelly could be used for that without the need to build and wire a board. Then i still need to search for an alternative :(
